version: '3.8'

services:
  redis:
    image: redis:7.0
    container_name: lms_redis
    ports:
      - "6380:6379"  # Using port 6380 instead
    volumes:
      - redis_data:/data

volumes:
  redis_data: