# Generated by Django 5.1.6 on 2025-02-23 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='courses',
        ),
    ]
