# Generated by Django 4.2.17 on 2025-03-24 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_coursecategory_remove_course_teacher_course_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.coursecategory'),
        ),
    ]
